name: Gradients
summary: Gradient tool writen in python
description: Gradient tool writen in python
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  Gradients:
    command: /pyqt+gradients.py 
    

parts:
 Gradients:
    plugin: python
    source: https://github.com/RobotDaniel/meme-calc/new/main
